  testpoint:
    image: perfsonar/testpoint:systemd-rocky8
    build:
      context: .
      dockerfile: systemd/Dockerfile
    cgroup: host
    environment:
      - TZ=UTC
    network_mode: "host"
    restart: on-failure
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tty: true
