version: '3.8'
services:
  testpoint:
    container_name: perfsonar-testpoint
    image: perfsonar/testpoint:latest
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    cap_add:
      - CAP_NET_BIND_SERVICE
    restart: on-failure
    volumes:
       - ./compose/psconfig:/etc/perfsonar/psconfig
